sources:
    - Carthage/Checkouts/cico_auto_codable/CICOAutoCodable
    - CICOPersistent
    - CICOPersistentDemo
    - CICOPersistentTests
templates:
    - Carthage/Checkouts/cico_auto_codable/sourcery/templates/show_all_type.stencil
    - Carthage/Checkouts/cico_auto_codable/sourcery/templates/cico_auto_codable.swifttemplate
    - sourcery/templates
output:
    sourcery/auto_generated
